# Generated by Django 5.2.17 on 2026-09-06 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=150)),
                ('result', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('WIN', 'Win'), ('LOSS', 'Loss'), ('DRAW', 'Draw')], default='SCHEDULED', max_length=10)),
                ('score_summary', models.CharField(blank=True, help_text='e.g. 3-1 (filled in once the match is played)', max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.team')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
