services:
  - type: web
    name: venom-academy
    runtime: python
    plan: free
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn venom_academy.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: venom-academy-db
          property: connectionString

databases:
  - name: venom-academy-db
    plan: free
    databaseName: venom_academy
    user: venom_user
