# Generated by Django 5.2.17 on 2026-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.AddField(
            model_name='coach',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='teams.team'),
        ),
    ]
