# Generated by Django 5.2.17 on 2026-09-06 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=150)),
                ('focus_area', models.CharField(blank=True, help_text='e.g. Fitness, Tactics, Set Pieces', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='teams.team')),
            ],
            options={
                'verbose_name': 'Training Session',
                'ordering': ['date', 'time'],
            },
        ),
    ]
